# TODO Fix this in the new version
MAPPINGS = [
    # sector_code, account_code, category name, cost type name
    ["ICR", "8800", "Indirect Costs", "Indirect Costs"],
    [None, "5210", "National Staff", None],
    [None, "5110", "National Staff", None],
    ["DSC", "6821", "Office Expenses", "Support Costs"],
    [None, "5310", "International Staff", None],
    [None, "5410", "International Staff", None],
    [None, "5591", "International Staff", None],
    [None, "6250", "Travel & Transport", None],
    [None, "5430", "International Staff", None],
    [None, "5330", "International Staff", None],
    ["DSC", "6810", "Office Expenses", "Support Costs"],
    [None, "6259", "Travel & Transport", None],
    [None, "6252", "Travel & Transport", None],
    [None, "5572", "International Staff", None],
    ["DSC", "6801", "Office Expenses", "Support Costs"],
    ["ECO", "8550", "Materials & Activities", "Program Costs"],
    ["ECO", "8580", "Materials & Activities", "Program Costs"],
    [None, "8500", "Materials & Activities", None],
    [None, "6217", "Non-Staff Personnel", None],
    ["DSC", "6802", "Office Expenses", "Support Costs"],
    [None, "8420", "Materials & Activities", None],
    [None, "5592", "International Staff", None],
    ["DSC", "6800", "Office Expenses", "Support Costs"],
    [None, "6509", "Travel & Transport", None],
    [None, "6219", "Non-Staff Personnel", None],
    [None, "6501", "Travel & Transport", None],
    ["DSC", "6823", "Office Expenses", "Support Costs"],
    [None, "6349", "Assets & Equipment", None],
    [None, "5610", "National Staff", None],
    ["DSC", "6808", "Office Expenses", "Support Costs"],
    [None, "6500", "Travel & Transport", None],
    ["DSC", "6700", "Office Expenses", "Support Costs"],
    [None, "5580", "International Staff", None],
    ["DSC", "6820", "Office Expenses", "Support Costs"],
    ["DSC", "6201", "Office Expenses", "Support Costs"],
    [None, "8600", "Sub-Grants", None],
    ["DSC", "6355", "Office Expenses", "Support Costs"],
    ["DSC", "6205", "Office Expenses", "Support Costs"],
    [None, "6505", "Travel & Transport", None],
    [None, "8000", "Materials & Activities", None],
    [None, "8605", "Sub-Grants", None],
    ["DSC", "6830", "Office Expenses", "Support Costs"],
    [None, "6258", "Travel & Transport", None],
    ["ECO", "8210", "Materials & Activities", "Program Costs"],
    [None, "5560", "International Staff", None],
    [None, "6340", "Assets & Equipment", None],
    ["DSC", "6805", "Office Expenses", "Support Costs"],
    [None, "5565", "International Staff", None],
    [None, "6218", "Non-Staff Personnel", None],
    ["ECO", "8610", "Sub-Grants", "Program Costs"],
    ["DEMO", "1111", "International Staff", "Program Costs"],
    ["DEMO", "1112", "Travel & Transport", "Program Costs"],
    ["DEMO", "1121", "International Staff", "Program Costs"],
    ["DEMO", "1122", "National Staff", "Program Costs"],
    ["DEMO", "1131", "National Staff", "Program Costs"],
]
