INTERVENTIONS = [
    {
        "name": "Access to Clean Water",
        "description": "Provision of sufficient quantity of safe water to meet the drinking and domestic needs of people in need, including support for construction or rehabilitation of taps, hand pumps, wells, or water trucking, with corresponding hygiene promotion.",
        "icon": "water",
        "group": "Environment",
        "output_metrics": ["NumberOfPersonYearsOfWaterAccess"],
    },
    {
        "name": "Access to Sanitation",
        "description": "Support for construction or rehabilitation of adequate, appropriate and acceptable latrines and other sanitation facilities to allow rapid, safe and secure access at all times, with corresponding hygiene promotion.",
        "icon": "latrine",
        "group": "Health",
        "output_metrics": ["NumberOfPersonYearsOfSanitationAccess"],
    },
    {
        "name": "Agricultural Training and Inputs",
        "description": "Support to farmers with training, seedlings, fertilizer, livestock, equipment, infrastructure, demo plots, value chains, value addition, etc., to improve agricultural productivity. Farmers can be reached through mechanisms like producer groups, savings groups, or Farmer Field Schools.",
        "icon": "agriculture",
        "group": "Education",
        "output_metrics": ["NumberOfPeople", "NumberOfDaysOfTraining"],
    },
    {
        "name": "Business Skills Training",
        "description": "Entrepreneurship skills training in marketing, accounting, business plan development, etc.",
        "icon": "business_training",
        "group": "Education",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Child Protection Case Management",
        "description": "Provision of case management services for "
        "children who are unaccompanied minors or "
        "at risk of trafficking and exploitation.",
        "icon": "at_risk_children",
        "group": "Community",
        "output_metrics": ["NumberOfChildren"],
    },
    {
        "name": "Child Friendly Safe Spaces and Learning",
        "description": "Provision of safe spaces for children to access free and structured play, recreation, leisure and learning activities; these spaces may provide health, nutrition and psychosocial support and other activities that restore a sense of normality and continuity.",
        "icon": "child_friendly_spaces",
        "group": "Community",
        "output_metrics": ["NumberOfChildren"],
    },
    {
        "name": "Conditional Cash Transfer",
        "description": "Provision of cash to households in need through physical or electronic cash or vouchers, with conditions that must be met before receiving a transfer.",
        "icon": "cash",
        "group": "Cash",
        "output_metrics": ["NumberOfHouseholds"],
    },
    {
        "name": "Community Accountability Program",
        "description": "Provision of social accountability programs to improve community leadership and governance.",
        "icon": "cash",
        "group": "Community",
        "output_metrics": ["NumberOfCommunities", "NumberOfPeople"],
    },
    {
        "name": "Family Planning Services",
        "description": "Provision of family planning and birth spacing services to prevent unintended pregnancy, including demand generation, health worker training, counseling, service provision, commodities supply, and self-managed contraception.",
        "icon": "family_planning",
        "group": "Health",
        "output_metrics": ["NumberOfCoupleYearsOfProtection", "NumberOfPeople"],
    },
    {
        "name": "Maternal Health Services",
        "description": "Provision and sensitization of obstetrics and gynecology services at health institutions for expecting mothers, including pre-natal and post-natal care.",
        "icon": "delivery",
        "group": "Health",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Food Assistance",
        "description": "Provision of safe and nutritious food commodities to households in need; or financing to support procurement and distribution of food.",
        "icon": "food_assistance",
        "group": "Health",
        "output_metrics": ["ValueOfItemsDistributed", "NumberOfHouseholds"],
    },
    {
        "name": "General Program",
        "description": "General program to provide intended outcomes for the benefit of people in need.",
        "icon": "cash",
        "group": "Health",
        "output_metrics": ["NumberOfOutputs"],
    },
    {
        "name": "Legal Aid Case Management",
        "description": "Provision of legal case management services on government documentation, access to social services, illegal detention, asylum, etc.",
        "icon": "legal_aid",
        "group": "Protection",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Mental Health and Psychosocial Support",
        "description": "Provision of services that support psychosocial well-being and address mental health issues.",
        "icon": "primary_healthcare_services",
        "group": "Health",
        "output_metrics": ["NumberOfConsultations", "NumberOfPeople"],
    },
    {
        "name": "Non-Food-Item (NFI) Distribution",
        "description": "Distribution of non-food items to households depending on the need and context, e.g. blankets, cooking stoves, fuel, tents, mosquito nets, clothes, buckets, soap, brushes, etc.",
        "icon": "nonfood_distribution",
        "group": "Health",
        "output_metrics": ["ValueOfItemsDistributed", "NumberOfHouseholds"],
    },
    {
        "name": "Parenting Skills Program",
        "description": "Provision of parenting skills and coaching to strengthen the capacities of caregivers to reduce violence in the lives of children and support their healthy development by introducing techniques parents can use to communicate and problem solve effectively with their children.",
        "icon": "child_friendly_spaces",
        "group": "Community",
        "output_metrics": ["NumberOfHouseholds"],
    },
    {
        "name": "Business Grants and Mentorship",
        "description": "Supporting entrepreneurs to develop viable business plans and create new microenterprises or grow existing microenterprises through cash grants and mentorship.",
        "icon": "business_grants",
        "group": "Economic",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Primary Health Care Services",
        "description": "Provision of primary health care services to prevent mortality, morbidity, and disability.",
        "icon": "primary_healthcare_services",
        "group": "Health",
        "output_metrics": ["NumberOfConsultations", "NumberOfPeople"],
    },
    {
        "name": "Immunization Services",
        "description": "Provision of vaccines to people and children in need, including cold-chain storage and transport, demand generation, health worker training, and service provision.",
        "icon": "vaccines",
        "group": "Health",
        "output_metrics": [
            "NumberOfDoses",
            "NumberOfPeople",
        ],
    },
    {
        "name": "GBV Case Management",
        "description": "Provision of essential health and psychosocial services to survivors of gender-based violence.",
        "icon": "gbv_survivors",
        "group": "Health",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Teacher Training",
        "description": "Provision of training for teachers and school management committees on topics such as pedagogy, classroom management, etc.",
        "icon": "teacher_development",
        "group": "Education",
        "output_metrics": ["NumberOfTeacherDaysOfTraining"],
    },
    {
        "name": "Teacher Professional Development",
        "description": "Provision of school-based facilitated forums for teachers to meet regularly to revisit content learned in a training workshop and to gain ongoing learning opportunities through peer discussions, including peer groups, learning circles, mentoring, coaching.",
        "icon": "teacher_development_ongoing",
        "group": "Education",
        "output_metrics": ["NumberOfTeacherYearsOfSupport"],
    },
    {
        "name": "Malnutrition Treatment",
        "description": "Treatment for moderate and severe acute malnutrition among children.",
        "icon": "malnutrition",
        "group": "Health",
        "output_metrics": ["NumberOfChildrenTreated", "NumberOfChildrenRecovered"],
    },
    {
        "name": "Unconditional Cash Transfer",
        "description": "Provision of cash to households in need through physical or electronic cash or vouchers, without conditions that must be met before receiving a transfer.",
        "icon": "cash",
        "group": "Cash",
        "output_metrics": ["ValueOfCashDistributed", "NumberOfHouseholds"],
        "subcomponent_labels": ["First", "Second", "Third", "Last"],
    },
    {
        "name": "Protection Case Management",
        "description": "General protection case management for vulnerable people.",
        "icon": "gbv_survivors",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Malnutrition Prevention",
        "description": "Prevention of moderate and severe acute malnutrition among children.",
        "icon": "malnutrition",
        "output_metrics": ["NumberOfCaregivers", "NumberOfChildren"],
    },
    {
        "name": "Remedial and Catch-Up Program",
        "description": "Provision of short-term education support to complement regular formal education for children and youth who are in-school, or to support re-entry to the formal education system for children and youth who had been actively attending school before a recent educational disruption.",
        "icon": "teacher_development",
        "output_metrics": ["NumberOfChildren"],
    },
    {
        "name": "Accelerated Education Program",
        "description": "Provision of basic education over an accelerated timeframe for out-of-school children and youth at formal or non-formal learning centers.",
        "icon": "teacher_development",
        "output_metrics": ["NumberOfChildren"],
    },
    {
        "name": "Early Childhood Development",
        "description": "Support to develop the cognitive, emotional, social, and physical potential of babies and young pre-school children in need through safe spaces, play and learn activities, training caregivers and frontline workers to provide nurturing environments, counselling caregivers to bolster their own well-being, etc.",
        "icon": "child_friendly_spaces",
        "output_metrics": ["NumberOfChildren", "NumberOfCaregivers"],
    },
    {
        "name": "Technical and Vocational Education and Training (TVET)",
        "description": "Provision of Technical and Vocational Education and Training (TVET) courses to train participants in various technical and vocational skills.",
        "icon": "business_training",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Apprenticeship and On-The-Job Training",
        "description": "Provision of apprenticeships and internships for people to gain relevant on-the-job training and hands-on experience through placements in private sector companies.",
        "icon": "business_training",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Cash For Work",
        "description": "Provision of cash to individuals, based on the number of days worked on a predefined community activity.",
        "icon": "business_grants",
        "output_metrics": ["NumberOfHouseholds"],
    },
    {
        "name": "Land Restoration",
        "description": "Support to farmers with training, seedlings, fertilizer, equipment, infrastructure, demo plots, value chains, etc., to restore land and ecosystems through approaches such as Agroforestry, FMNR, tree planting, soil and water conservation, etc.",
        "icon": "agriculture",
        "output_metrics": ["NumberOfPeople", "NumberOfHectares"],
    },
    {
        "name": "Life Skills Curriculum and Training",
        "description": "Provision of life skills curriculum and training to improve the protection and empowerment of program participants, including safe spaces, learning sessions, mentors and facilitators, caregiver and community engagement.",
        "icon": "teacher_development",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "School Feeding Program",
        "description": "Provision of meals and other services for children in schools and/or take-home rations to improve enrollment, attendance, attention span, and literacy.",
        "icon": "malnutrition",
        "output_metrics": ["NumberOfChildren", "NumberOfMeals"],
    },
    {
        "name": "Integrated Community Case Management (iCCM)",
        "description": "Diagnosis, treatment, and referral of common childhood illnesses (e.g., pneumonia, diarrhea, malaria) through community health workers.",
        "icon": "primary_healthcare_services",
        "output_metrics": ["NumberOfConsultations", "NumberOfChildren"],
    },
    {
        "name": "Non-Communicable Diseases Care",
        "description": "Prevention and control of non-communicable diseases.",
        "icon": "primary_healthcare_services",
        "output_metrics": ["NumberOfConsultations", "NumberOfPeople"],
    },
    {
        "name": "Safe Abortion Care",
        "description": "Provision of safe abortion care (SAC) services, including comprehensive abortion care (CAC), post-abortion care (PAC), and self-managed abortion care.",
        "icon": "gbv_survivors",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Employment Skills Training",
        "description": "Employment skills training on CV writing, job hunting, interview skills, etc.",
        "icon": "business_training",
        "output_metrics": ["NumberOfPeople"],
    },
    {
        "name": "Graduation Program",
        "description": "A holistic approach to tackle simultaneously the interrelated challenges faced by the poorest with a set of services over several years, including access to saving services, intensive mentoring, technical skills training, and the grant of a productive asset and/or seed capital.",
        "icon": "business_training",
        "output_metrics": ["NumberOfHouseholds"],
    },
    {
        "name": "Savings Groups",
        "description": "Creating and supporting savings groups such as Village Savings and Loans Associations (VSLA), Youth Savings and Loans Associations (YSLA), Urban Savings and Loans Associations (USLA), Self Help Groups (SHG).",
        "icon": "business_training",
        "output_metrics": ["NumberOfGroups", "NumberOfPeople"],
    },
    {
        "name": "Infant and Young Child Feeding (IYCF)",
        "description": "Training and support to caregivers and health workers on safe and appropriate infant and young child feeding practices to improve the nutritional status and survival of children under two years of age, including breastfeeding, correct use of adequate complementary foods, community awareness, etc.",
        "icon": "malnutrition",
        "output_metrics": ["NumberOfCaregivers", "NumberOfChildren"],
    },
    {
        "name": "Women and Girls' Safe Spaces",
        "description": "Provision of a structured place where women’s and adolescent girls’ physical and emotional safety is respected and where they are supported through processes of empowerment to seek, share, and obtain information, access services, express themselves, enhance psychosocial well-being, and realize their rights.",
        "icon": "gbv_survivors",
        "output_metrics": ["NumberOfPeople"],
    },
]
