"""Intervention metadata definitions: the optional fields an administrator configures per intervention.

Values live on each InterventionInstance (``metadata``), keyed by a field's ``key``; choice
selections are option keys. Keys are generated by the server and never derived from names or
positions, so renaming and reordering keep values, while a saved type change rotates the field key
and thereby retires the old values (see ``website.intervention_metadata``).
"""

import uuid

from django.db import models
from django.db.models import F, Q
from django.db.models.functions import Lower
from django.utils.translation import gettext_lazy as _

MAX_FIELDS_PER_INTERVENTION = 20
MAX_OPTIONS_PER_FIELD = 10
NAME_MAX_LENGTH = 100
FREE_TEXT_MAX_LENGTH = 255
NUMBER_MAX_DIGITS = 20


class MetadataFieldType(models.TextChoices):
    FREE_TEXT = "free_text", _("Free Text")
    MULTIPLE_CHOICE = "multiple_choice", _("Multiple Choice")
    SINGLE_CHOICE = "single_choice", _("Single Choice")
    NUMBER = "number", _("Number")


class MetadataNumberType(models.TextChoices):
    INTEGER = "integer", _("Integer")
    DECIMAL = "decimal", _("Decimal")
    PERCENTAGE = "percentage", _("Percentage")
    CURRENCY = "currency", _("Currency")


CHOICE_FIELD_TYPES = (MetadataFieldType.MULTIPLE_CHOICE, MetadataFieldType.SINGLE_CHOICE)


class InterventionMetadataField(models.Model):
    intervention = models.ForeignKey(
        "website.Intervention", on_delete=models.CASCADE, related_name="metadata_fields"
    )
    # The storage key for values on intervention instances. Rotated on a type change.
    key = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    name = models.CharField(verbose_name=_("Name"), max_length=NAME_MAX_LENGTH)
    field_type = models.CharField(verbose_name=_("Type"), max_length=20, choices=MetadataFieldType)
    number_type = models.CharField(
        verbose_name=_("Number type"), max_length=20, choices=MetadataNumberType, null=True, blank=True
    )
    order = models.IntegerField(default=0)

    class Meta:
        verbose_name = _("Intervention Metadata Field")
        verbose_name_plural = _("Intervention Metadata Fields")
        ordering = ["order", "pk"]
        constraints = [
            # Names are unique within an intervention regardless of case (trimmed by the forms).
            models.UniqueConstraint(
                Lower("name"), F("intervention"), name="unique_metadata_field_name_per_intervention"
            ),
            # A Number field has a number type; nothing else does.
            models.CheckConstraint(
                condition=(
                    Q(field_type=MetadataFieldType.NUMBER, number_type__isnull=False)
                    | (~Q(field_type=MetadataFieldType.NUMBER) & Q(number_type__isnull=True))
                ),
                name="metadata_field_number_type_matches_field_type",
            ),
        ]

    def __str__(self):
        return self.name

    @property
    def is_choice(self) -> bool:
        return self.field_type in CHOICE_FIELD_TYPES

    @property
    def is_number(self) -> bool:
        return self.field_type == MetadataFieldType.NUMBER

    @property
    def storage_key(self) -> str:
        return str(self.key)

    def rotate_key(self) -> None:
        """Retire the current storage key: values stored under it are no longer this field's."""
        self.key = uuid.uuid4()


class InterventionMetadataOption(models.Model):
    field = models.ForeignKey(InterventionMetadataField, on_delete=models.CASCADE, related_name="options")
    # The value stored for a selection of this option; survives relabelling and reordering.
    key = models.UUIDField(default=uuid.uuid4, unique=True, editable=False)
    label = models.CharField(verbose_name=_("Label"), max_length=NAME_MAX_LENGTH)
    order = models.IntegerField(default=0)

    class Meta:
        verbose_name = _("Intervention Metadata Option")
        verbose_name_plural = _("Intervention Metadata Options")
        ordering = ["order", "pk"]

    def __str__(self):
        return self.label

    @property
    def storage_key(self) -> str:
        return str(self.key)
