# Generated by Django 2.2.3 on 2020-05-06 21:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_log", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "App Log Subscription",
                "verbose_name_plural": "App Log Subscriptions",
            },
        ),
    ]
