# Generated by Django 3.2.7 on 2021-09-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_log", "0002_auto_20200506_1415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="notifier_config",
            field=models.JSONField(default=dict),
        ),
    ]
