# Generated by Django 5.2.4 on 2025-07-25 05:21

import ckeditor.fields
import django.core.validators
import django.db.models.deletion
import ombucore.admin.fields
import website.models.fields
import website.models.mixins
import website.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountCodeDescription",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "account_code",
                    models.CharField(max_length=255, verbose_name="Account Code"),
                ),
                (
                    "account_description",
                    models.CharField(max_length=255, verbose_name="Account Description"),
                ),
                (
                    "sensitive_data",
                    models.BooleanField(
                        default=False,
                        help_text="When checked, costs and transactions will not be shown for this account code.",
                        verbose_name="Contains sensitive data",
                    ),
                ),
            ],
            options={
                "verbose_name": "Account Code Description",
                "verbose_name_plural": "Account Code Description",
            },
        ),
        migrations.CreateModel(
            name="AnalysisType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
            ],
            options={
                "verbose_name": "Analysis Type",
                "verbose_name_plural": "Analyses Types",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("description", models.TextField(verbose_name="Description")),
                ("order", models.PositiveIntegerField(verbose_name="Sort Order")),
                (
                    "help_text",
                    ckeditor.fields.RichTextField(blank=True, verbose_name="Allocation Suggestion Help Text"),
                ),
                ("default", models.BooleanField(default=False, verbose_name="Default")),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["order"],
            },
            bases=(website.models.mixins.OrderableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="CostType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Label")),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            (10, "Program Costs"),
                            (20, "Support Costs"),
                            (30, "Indirect Costs"),
                        ],
                        default=10,
                        unique=True,
                        verbose_name="Type",
                    ),
                ),
                ("order", models.PositiveIntegerField(verbose_name="Sort Order")),
                ("default", models.BooleanField(default=False, verbose_name="Default")),
            ],
            options={
                "verbose_name": "Cost Type",
                "verbose_name_plural": "Cost Types",
                "ordering": ["type", "order"],
            },
            bases=(website.models.mixins.OrderableMixin, models.Model),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
                ("code", models.CharField(max_length=10, verbose_name="Code")),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="If selected, new user accounts will be assigned this country as the account's primary country.",
                        verbose_name="Default country for new users",
                    ),
                ),
                (
                    "always_include_costs",
                    models.BooleanField(
                        default=False,
                        help_text="If selected, cost items from this country will always be imported, regardless of the country filters configured for the analysis or the instance",
                        verbose_name="Always include costs from this country into analyses",
                    ),
                ),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FieldLabelOverrides",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tr_date",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="Date"),
                ),
                (
                    "tr_date_overridden",
                    models.BooleanField(default=False, verbose_name="Overridden"),
                ),
                (
                    "tr_site_code",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="Site Code"),
                ),
                (
                    "tr_site_code_overridden",
                    models.BooleanField(default=False, verbose_name="Overridden"),
                ),
                (
                    "tr_amount",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="Amount"),
                ),
                (
                    "tr_amount_overridden",
                    models.BooleanField(default=False, verbose_name="Overridden"),
                ),
                (
                    "ci_grant_code",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="Grant Code"),
                ),
                (
                    "ci_grant_code_overridden",
                    models.BooleanField(default=False, verbose_name="Overridden"),
                ),
                (
                    "ci_site_code",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="Site Code"),
                ),
                (
                    "ci_site_code_overridden",
                    models.BooleanField(default=False, verbose_name="Overridden"),
                ),
                (
                    "ci_cost_type",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="Cost Type"),
                ),
                (
                    "ci_cost_type_overridden",
                    models.BooleanField(default=False, verbose_name="Overridden"),
                ),
                (
                    "ci_total_cost",
                    models.CharField(blank=True, max_length=40, null=True, verbose_name="Total Cost"),
                ),
                (
                    "ci_total_cost_overridden",
                    models.BooleanField(default=False, verbose_name="Overridden"),
                ),
            ],
            options={
                "verbose_name": "Field Label Overrides",
                "verbose_name_plural": "Field Label Overrides",
            },
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "icon",
                    models.CharField(
                        choices=[
                            ("water", "Access to Clean Water"),
                            ("agriculture", "Agricultural Extension Support"),
                            ("business_training", "Business Skills Training"),
                            ("at_risk_children", "Case Mangement for At-Risk Children"),
                            ("child_friendly_spaces", "Child Friendly Spaces"),
                            (
                                "family_planning",
                                "Distribution of Family Planning Supplies",
                            ),
                            (
                                "delivery",
                                "Encouraging Women to Deliver at Health Institutions",
                            ),
                            ("food_assistance", "Food Assistance"),
                            ("latrine", "Latrine-building Program"),
                            ("legal_aid", "Legal Aid"),
                            ("nonfood_distribution", "Non-food-item Distribution"),
                            ("business_grants", "Providing Business Grants"),
                            (
                                "primary_healthcare_services",
                                "Provision of Primary Healthcare Services",
                            ),
                            ("vaccines", "Provision of Vaccines"),
                            (
                                "gbv_survivors",
                                "Supporting Gender-based Violence Survivors at Women's Centers",
                            ),
                            (
                                "teacher_development",
                                "Teacher Development: Face-to-face Training",
                            ),
                            (
                                "teacher_development_ongoing",
                                "Teacher Development: Ongoing Professional Support",
                            ),
                            ("malnutrition", "Treatment for Severe Acute Malnutrition"),
                            ("cash", "Unconditional Cash Distribution"),
                            ("villages", "Villages"),
                        ],
                        default="cash",
                        max_length=255,
                    ),
                ),
                (
                    "output_metrics",
                    website.models.fields.ChoiceArrayField(
                        base_field=models.CharField(
                            blank=True,
                            choices=[
                                ("NumberOfCaregivers", "Number of Caregivers"),
                                ("NumberOfChildren", "Number of Children"),
                                (
                                    "NumberOfChildrenRecovered",
                                    "Number of Children Recovered",
                                ),
                                (
                                    "NumberOfChildrenTreated",
                                    "Number of Children Treated (Excluding Defaulters)",
                                ),
                                ("NumberOfClients", "Number of Clients"),
                                ("NumberOfCommunities", "Number of Communities"),
                                ("NumberOfConsultations", "Number of Consultations"),
                                (
                                    "NumberOfCoupleYearsOfProtection",
                                    "Number of Couple-Years of Protection (CYPs)",
                                ),
                                (
                                    "NumberOfDaysOfTraining",
                                    "Number of Days of Training",
                                ),
                                ("NumberOfDoses", "Number of Doses"),
                                ("NumberOfGroups", "Number of Groups"),
                                ("NumberOfHectares", "Number of Hectares"),
                                ("NumberOfHouseholds", "Number of Households"),
                                ("NumberOfMeals", "Number of Meals"),
                                ("NumberOfOutputs", "Number of Outputs"),
                                ("NumberOfParticipants", "Number of Participants"),
                                ("NumberOfPeople", "Number of People"),
                                (
                                    "NumberOfPersonYearsOfSanitationAccess",
                                    "Number of Person-Years of Sanitation Access",
                                ),
                                (
                                    "NumberOfPersonYearsOfWaterAccess",
                                    "Number of Person-Years of Water Access",
                                ),
                                (
                                    "NumberOfTeacherDaysOfTraining",
                                    "Number of Teacher-Days of Training",
                                ),
                                (
                                    "NumberOfTeacherYearsOfSupport",
                                    "Number of Teacher-Years of Support",
                                ),
                                ("NumberOfWomen", "Number of Women"),
                                (
                                    "ValueOfBusinessGrantAmount",
                                    "Value of Business Grant Amount",
                                ),
                                ("ValueOfCashDistributed", "Value of Cash Distributed"),
                                (
                                    "ValueOfItemsDistributed",
                                    "Value of Items Distributed",
                                ),
                            ],
                            max_length=255,
                        ),
                        default=list,
                        size=None,
                        verbose_name="Output Metrics",
                    ),
                ),
                (
                    "show_in_menu",
                    models.BooleanField(
                        default=True,
                        help_text="When checked, this intervention insights page will be accessible from the Program Design Lessons menu.",
                        verbose_name="Show this intervention in the Program Design Lessons menu",
                    ),
                ),
                (
                    "subcomponent_labels",
                    website.models.fields.TypedJsonField(blank=True, default=list, null=True),
                ),
            ],
            options={
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InterventionGroup",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Intervention Group",
                "verbose_name_plural": "Intervention Groups",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "region_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Region Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Region",
                "verbose_name_plural": "Regions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Settings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "google_analytics_code",
                    models.CharField(
                        blank=True,
                        help_text='E.g. "UA-10304692-04"',
                        max_length=100,
                        null=True,
                        verbose_name="Google Analytics tracking ID",
                    ),
                ),
                (
                    "show_transactions",
                    models.BooleanField(
                        default=True,
                        help_text="If enabled, the underlying transactions for all cost line items will be displayed, if available.",
                        verbose_name="Show Transaction Data",
                    ),
                ),
                (
                    "budget_upload_template",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="",
                        verbose_name="Budget Upload Template",
                    ),
                ),
                (
                    "instance_logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="",
                        validators=[
                            website.validators.FileSizeValidator(),
                            django.core.validators.validate_image_file_extension,
                        ],
                        verbose_name="Instance Logo",
                    ),
                ),
                (
                    "paginate_by",
                    models.IntegerField(
                        choices=[(10, "10"), (25, "25"), (50, "50"), (100, "100")],
                        default=25,
                        verbose_name="Paginate by",
                    ),
                ),
                (
                    "transaction_country_filter",
                    models.BooleanField(
                        default=False,
                        help_text="If enabled, transactions loaded from the transaction data store for each analysis will be limited to the country selected.",
                        verbose_name="Transaction Country Filter",
                    ),
                ),
            ],
            options={
                "verbose_name": "Settings",
                "verbose_name_plural": "Settings",
            },
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Source"),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("start_date", models.DateField(verbose_name="Start Date")),
                ("end_date", models.DateField(verbose_name="End Date")),
                ("grants", models.CharField(max_length=255)),
                ("output_costs", models.JSONField(default=dict)),
                (
                    "currency_code",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("USD", "US dollars"),
                            ("GBP", "British Pound sterling"),
                            ("EUR", "Euros"),
                        ],
                        default="",
                        max_length=255,
                        verbose_name="Currency code",
                    ),
                ),
                (
                    "output_count_source",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Output count data source",
                    ),
                ),
                (
                    "needs_transaction_resync",
                    models.BooleanField(default=False, editable=False),
                ),
                (
                    "efficiency_lesson",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="What did we learn about the cost-efficiency of this intervention?",
                        null=True,
                    ),
                ),
                (
                    "breakdown_lesson",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="Do the proportion of these cost categories look reasonable?",
                        null=True,
                    ),
                ),
                (
                    "other_hq_costs",
                    models.BooleanField(
                        default=False,
                        help_text="HQ costs that were not captured in the finance data",
                        verbose_name="Other HQ Costs",
                    ),
                ),
                (
                    "in_kind_contributions",
                    models.BooleanField(
                        default=False,
                        help_text="Goods and services donated by other actors",
                        verbose_name="In-Kind Contributions",
                    ),
                ),
                (
                    "client_time",
                    models.BooleanField(
                        default=False,
                        help_text="Time spent by people participating in the program",
                        verbose_name="Client Time",
                    ),
                ),
                (
                    "all_transactions_total_cost",
                    models.CharField(
                        blank=True,
                        help_text="The Total Cost of every transaction corresponding to this Analysis, regardless of Country",
                        max_length=512,
                        null=True,
                        verbose_name="All Transactions Total Cost, Comma separated by Grant",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.analysis",
                    ),
                ),
                (
                    "owner",
                    ombucore.admin.fields.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analysis_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="website.analysistype",
                        verbose_name="What data is this analysis based on?",
                    ),
                ),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="website.country",
                        verbose_name="Country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis",
                "verbose_name_plural": "Analyses",
            },
        ),
        migrations.CreateModel(
            name="AnalysisCostTypeCategory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "confirmed",
                    models.BooleanField(default=False, verbose_name="Confirmed?"),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_type_categories",
                        to="website.analysis",
                        verbose_name="Analysis",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.analysiscosttypecategory",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="website.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "cost_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="website.costtype",
                        verbose_name="CostType",
                    ),
                ),
            ],
            options={
                "ordering": ["cost_type__order", "category__order"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisCostTypeCategoryGrant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grant", models.CharField(max_length=255, verbose_name="Grant")),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.analysiscosttypecategorygrant",
                    ),
                ),
                (
                    "cost_type_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cost_type_category_grants",
                        to="website.analysiscosttypecategory",
                        verbose_name="CostType Category",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "cost_type_category__cost_type__type",
                    "cost_type_category__cost_type__order",
                    "grant",
                    "cost_type_category__category__order",
                ],
            },
        ),
        migrations.CreateModel(
            name="CostLineItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Country code",
                    ),
                ),
                (
                    "grant_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Grant code",
                    ),
                ),
                (
                    "budget_line_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Budget line code",
                    ),
                ),
                (
                    "account_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Account code",
                    ),
                ),
                (
                    "site_code",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Site code"),
                ),
                (
                    "sector_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Sector code",
                    ),
                ),
                (
                    "budget_line_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="Budget line description",
                    ),
                ),
                (
                    "total_cost",
                    models.DecimalField(decimal_places=4, max_digits=14, verbose_name="Total cost"),
                ),
                (
                    "loe_or_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="LOE or Unit",
                    ),
                ),
                (
                    "months_or_unit",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Months or Unit",
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Unit cost",
                    ),
                ),
                (
                    "quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=14,
                        null=True,
                        verbose_name="Quantity",
                    ),
                ),
                (
                    "dummy_field_1",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Dummy field 1",
                    ),
                ),
                (
                    "dummy_field_2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Dummy field 2",
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, default="", max_length=2048, verbose_name="Note"),
                ),
                (
                    "is_special_lump_sum",
                    models.BooleanField(default=False, verbose_name="Special Country Lump Sum Cost Item"),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unfiltered_cost_line_items",
                        to="website.analysis",
                        verbose_name="Analysis",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.costlineitem",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Line Item",
                "verbose_name_plural": "Cost Line Items",
            },
        ),
        migrations.CreateModel(
            name="CostLineItemConfig",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_cost_type",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "CLIENT_TIME"), (2, "IN_KIND"), (3, "OTHER_HQ")],
                        null=True,
                    ),
                ),
                (
                    "subcomponent_analysis_allocations",
                    website.models.fields.TypedJsonField(default=dict, null=True),
                ),
                (
                    "subcomponent_analysis_allocations_skipped",
                    models.BooleanField(default=False),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.costlineitemconfig",
                    ),
                ),
                (
                    "cost_line_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="config",
                        to="website.costlineitem",
                        verbose_name="Cost Line Item",
                    ),
                ),
                (
                    "cost_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.costtype",
                        verbose_name="Cost Type",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CostTypeCategoryMapping",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Country code",
                    ),
                ),
                (
                    "grant_code",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Grant code"),
                ),
                (
                    "budget_line_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Budget line code",
                    ),
                ),
                (
                    "account_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Account code",
                    ),
                ),
                (
                    "site_code",
                    models.CharField(blank=True, max_length=255, null=True, verbose_name="Site code"),
                ),
                (
                    "sector_code",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Sector code",
                    ),
                ),
                (
                    "budget_line_description",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        null=True,
                        verbose_name="Budget line description",
                    ),
                ),
                (
                    "category",
                    ombucore.admin.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.category",
                        verbose_name="Category",
                    ),
                ),
                (
                    "cost_type",
                    ombucore.admin.fields.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="website.costtype",
                        verbose_name="Cost Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Type / Category Mapping",
                "verbose_name_plural": "Cost Type / Category Mappings",
            },
        ),
        migrations.CreateModel(
            name="InsightComparisonData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                ("grants", models.CharField(max_length=255)),
                ("parameters", models.JSONField(default=dict)),
                ("output_costs", models.JSONField(default=dict)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="website.country",
                        verbose_name="Country",
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="website.intervention",
                        verbose_name="Intervention Being Analyzed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Insight Comparison Data Point",
                "verbose_name_plural": "Insight Comparison Data",
            },
        ),
        migrations.CreateModel(
            name="CostEfficiencyStrategy",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                (
                    "efficiency_driver_description",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        null=True,
                        verbose_name="Efficiency Driver description",
                    ),
                ),
                (
                    "strategy_to_improve_description",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        null=True,
                        verbose_name="Strategy to Improve Cost-Efficiency description",
                    ),
                ),
                (
                    "interventions",
                    ombucore.admin.fields.ManyToManyField(
                        help_text=None,
                        to="website.intervention",
                        verbose_name="Intervention Being Analyzed",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cost Efficiency Strategy",
                "verbose_name_plural": "Cost Efficiency Strategies",
                "ordering": ["title"],
            },
        ),
        migrations.AddField(
            model_name="intervention",
            name="group",
            field=ombucore.admin.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="interventions",
                to="website.interventiongroup",
            ),
        ),
        migrations.CreateModel(
            name="InterventionInstance",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=100, null=True)),
                ("order", models.IntegerField(default=0)),
                ("parameters", website.models.fields.TypedJsonField(default=dict)),
                (
                    "analysis",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.analysis",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.interventioninstance",
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.intervention",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CostLineItemInterventionAllocation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocation",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        max_digits=7,
                        null=True,
                        verbose_name="% allocation to intervention",
                    ),
                ),
                (
                    "cli_config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="website.costlineitemconfig",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.costlineiteminterventionallocation",
                    ),
                ),
                (
                    "intervention_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.interventioninstance",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisCostTypeCategoryGrantIntervention",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.analysiscosttypecategorygrantintervention",
                    ),
                ),
                (
                    "cost_type_grant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contributors",
                        to="website.analysiscosttypecategorygrant",
                    ),
                ),
                (
                    "intervention_instance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="website.interventioninstance",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="analysis",
            name="interventions",
            field=models.ManyToManyField(
                related_name="analyses",
                through="website.InterventionInstance",
                to="website.intervention",
                verbose_name="Intervention Being Analyzed",
            ),
        ),
        migrations.AddField(
            model_name="country",
            name="region",
            field=ombucore.admin.fields.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="website.region",
                verbose_name="Region",
            ),
        ),
        migrations.CreateModel(
            name="SubcomponentCostAnalysis",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subcomponent_labels",
                    website.models.fields.TypedJsonField(blank=True, default=list, null=True),
                ),
                ("subcomponent_labels_confirmed", models.BooleanField(default=False)),
                (
                    "analysis",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subcomponent_cost_analysis",
                        to="website.analysis",
                        verbose_name="Analysis",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.subcomponentcostanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Subcomponent Cost Analysis",
                "verbose_name_plural": "Subcomponent Cost Analyses",
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                (
                    "country_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=10,
                        verbose_name="Country code",
                    ),
                ),
                (
                    "grant_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Grant code",
                    ),
                ),
                (
                    "budget_line_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Budget line code",
                    ),
                ),
                (
                    "account_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Account code",
                    ),
                ),
                (
                    "site_code",
                    models.CharField(blank=True, default="", max_length=255, verbose_name="Site code"),
                ),
                (
                    "sector_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Sector code",
                    ),
                ),
                (
                    "transaction_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Transaction code",
                    ),
                ),
                (
                    "transaction_description",
                    models.TextField(blank=True, default="", verbose_name="Transaction description"),
                ),
                (
                    "currency_code",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Currency code",
                    ),
                ),
                (
                    "budget_line_description",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=1000,
                        verbose_name="Budget line description",
                    ),
                ),
                (
                    "amount_in_instance_currency",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        verbose_name="Amount, in instance currency",
                    ),
                ),
                (
                    "amount_in_source_currency",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=14,
                        verbose_name="Amount, in source currency",
                    ),
                ),
                (
                    "dummy_field_1",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Dummy field 1",
                    ),
                ),
                (
                    "dummy_field_2",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Dummy field 2",
                    ),
                ),
                (
                    "dummy_field_3",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Dummy field 3",
                    ),
                ),
                (
                    "dummy_field_4",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Dummy field 4",
                    ),
                ),
                (
                    "dummy_field_5",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Dummy field 5",
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="website.analysis",
                        verbose_name="Analysis",
                    ),
                ),
                (
                    "cloned_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="website.transaction",
                    ),
                ),
                (
                    "cost_line_item",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="website.costlineitem",
                        verbose_name="Cost Line Item",
                    ),
                ),
            ],
            options={
                "verbose_name": "Transaction",
                "verbose_name_plural": "Transaction",
            },
        ),
        migrations.AddIndex(
            model_name="costlineitem",
            index=models.Index(
                fields=[
                    "country_code",
                    "grant_code",
                    "budget_line_code",
                    "account_code",
                    "site_code",
                    "sector_code",
                ],
                name="website_cos_country_2ad4fb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="costlineiteminterventionallocation",
            constraint=models.UniqueConstraint(
                fields=("cli_config", "intervention_instance"),
                name="unique_cli_config_intervention",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="analysiscosttypecategorygrantintervention",
            unique_together={("cost_type_grant", "intervention_instance")},
        ),
        migrations.AddIndex(
            model_name="transaction",
            index=models.Index(
                fields=[
                    "country_code",
                    "grant_code",
                    "budget_line_code",
                    "account_code",
                    "site_code",
                    "sector_code",
                ],
                name="website_tra_country_a97cbc_idx",
            ),
        ),
    ]
