# Generated by Django 5.2.4 on 2026-07-13 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "website",
            "0004_remove_subcomponentcostanalysis_subcomponent_labels_confirmed",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interventioninstance",
            options={
                "verbose_name": "Intervention",
                "verbose_name_plural": "Interventions",
            },
        ),
    ]
