# Generated by Django 5.2.4 on 2026-07-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0002_settings_transaction_data_template"),
        ("website", "0005_alter_interventioninstance_options"),
    ]

    operations = []
