# Generated by Django 5.2.4 on 2026-08-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0007_remove_subcomponent_husks"),
    ]

    operations = [
        migrations.AddField(
            model_name="costlineitem",
            name="dummy_field_3",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Dummy field 3"),
        ),
        migrations.AddField(
            model_name="costlineitem",
            name="dummy_field_4",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Dummy field 4"),
        ),
        migrations.AddField(
            model_name="costlineitem",
            name="dummy_field_5",
            field=models.CharField(blank=True, default="", max_length=255, verbose_name="Dummy field 5"),
        ),
    ]
