# Generated by Django 5.2.4 on 2026-08-18 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0008_costlineitem_dummy_field_3_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_1",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Budget Custom Field 1",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_1_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_2",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Budget Custom Field 2",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_2_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_3",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Budget Custom Field 3",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_3_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_4",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Budget Custom Field 4",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_4_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_5",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Budget Custom Field 5",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_dummy_field_5_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_1",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Transaction Custom Field 1",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_1_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_2",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Transaction Custom Field 2",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_2_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_3",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Transaction Custom Field 3",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_3_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_4",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Transaction Custom Field 4",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_4_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_5",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Transaction Custom Field 5",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="tr_dummy_field_5_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
    ]
