# Generated by Django 5.2.4 on 2026-08-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0009_fieldlabeloverrides_ci_dummy_field_1_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="settings",
            name="budget_upload_template",
            field=models.FileField(
                blank=True,
                help_text="Optional override. Leave blank -- or tick Clear -- to offer a template generated from the columns the budget importer actually reads, including any custom fields. Upload a file only if this instance needs a bespoke template.",
                null=True,
                upload_to="",
                verbose_name="Budget Upload Template",
            ),
        ),
    ]
