# Generated by Django 5.2.4 on 2026-09-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0010_alter_settings_budget_upload_template"),
    ]

    operations = [
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_account_code",
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="Account Code"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_account_code_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_budget_line_description",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                verbose_name="Budget Line Description",
            ),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_budget_line_description_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_sector_code",
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name="Sector Code"),
        ),
        migrations.AddField(
            model_name="fieldlabeloverrides",
            name="ci_sector_code_overridden",
            field=models.BooleanField(default=False, verbose_name="Overridden"),
        ),
    ]
