# Generated by Django 5.2.4 on 2026-10-01 05:44

import django.db.models.deletion
import django.db.models.functions.text
import uuid
import website.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("website", "0012_analysis_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="interventioninstance",
            name="metadata",
            field=website.models.fields.TypedJsonField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="InterventionMetadataField",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Name")),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("free_text", "Free Text"),
                            ("multiple_choice", "Multiple Choice"),
                            ("single_choice", "Single Choice"),
                            ("number", "Number"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                (
                    "number_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("integer", "Integer"),
                            ("decimal", "Decimal"),
                            ("percentage", "Percentage"),
                            ("currency", "Currency"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Number type",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_fields",
                        to="website.intervention",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention Metadata Field",
                "verbose_name_plural": "Intervention Metadata Fields",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.CreateModel(
            name="InterventionMetadataOption",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("label", models.CharField(max_length=100, verbose_name="Label")),
                ("order", models.IntegerField(default=0)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="options",
                        to="website.interventionmetadatafield",
                    ),
                ),
            ],
            options={
                "verbose_name": "Intervention Metadata Option",
                "verbose_name_plural": "Intervention Metadata Options",
                "ordering": ["order", "pk"],
            },
        ),
        migrations.AddConstraint(
            model_name="interventionmetadatafield",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                models.F("intervention"),
                name="unique_metadata_field_name_per_intervention",
            ),
        ),
        migrations.AddConstraint(
            model_name="interventionmetadatafield",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("field_type", "number"), ("number_type__isnull", False)),
                    models.Q(
                        models.Q(("field_type", "number"), _negated=True),
                        ("number_type__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="metadata_field_number_type_matches_field_type",
            ),
        ),
    ]
