# Generated by Django 5.2.4 on 2025-07-25 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("otp_hotp", "0003_add_timestamps"),
    ]

    operations = [
        migrations.CreateModel(
            name="HOTPEmailDevice",
            fields=[
                (
                    "hotpdevice_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="otp_hotp.hotpdevice",
                    ),
                ),
                ("token_creation_datetime", models.DateTimeField(auto_now=True)),
                (
                    "token_validity_time",
                    models.IntegerField(default=3600, help_text="Number of seconds token is valid for."),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("otp_hotp.hotpdevice",),
        ),
    ]
