# Generated by Django 1.10.5 on 2017-03-02 17:49


import django.utils.timezone
import taggit_autosuggest.managers
from django.db import migrations, models

import ombucore.assets.validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("taggit", "0002_auto_20150616_2121"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Asset",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
            ],
            options={
                "ordering": ["-created"],
                "verbose_name": "Asset",
                "verbose_name_plural": "Assets",
            },
        ),
        migrations.CreateModel(
            name="AssetFolder",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "created",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
                "verbose_name": "Folder",
            },
        ),
        migrations.CreateModel(
            name="DocumentAsset",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.Asset",
                    ),
                ),
                (
                    "document",
                    models.FileField(
                        upload_to="doc",
                        validators=[
                            ombucore.assets.validators.FileExtensionValidator(
                                (
                                    "ppt",
                                    "pptx",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "xls",
                                    "xlt",
                                    "txt",
                                    "ZIP",
                                )
                            )
                        ],
                    ),
                ),
                ("file_type", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Document",
                "verbose_name_plural": "Documents",
            },
            bases=("assets.asset",),
        ),
        migrations.CreateModel(
            name="ImageAsset",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.Asset",
                    ),
                ),
                (
                    "image",
                    models.ImageField(height_field="height", upload_to="img", width_field="width"),
                ),
                ("width", models.CharField(blank=True, max_length=20)),
                ("height", models.CharField(blank=True, max_length=20)),
            ],
            options={
                "verbose_name": "Image",
                "verbose_name_plural": "Images",
            },
            bases=("assets.asset",),
        ),
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                (
                    "asset_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="assets.Asset",
                    ),
                ),
                (
                    "video_url",
                    models.CharField(max_length=255, verbose_name="Video URL"),
                ),
                (
                    "transcript",
                    models.FileField(
                        blank=True,
                        upload_to=b"",
                        validators=[ombucore.assets.validators.FileExtensionValidator(("pdf",))],
                        verbose_name="Transcript",
                    ),
                ),
                ("provider", models.CharField(blank=True, max_length=200)),
                ("thumbnail_url", models.CharField(blank=True, max_length=255)),
                ("thumbnail_width", models.CharField(blank=True, max_length=100)),
                ("thumbnail_height", models.CharField(blank=True, max_length=100)),
                ("width", models.CharField(blank=True, max_length=100)),
                ("height", models.CharField(blank=True, max_length=100)),
                ("html", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Video",
                "verbose_name_plural": "Videos",
            },
            bases=("assets.asset",),
        ),
        migrations.AddField(
            model_name="asset",
            name="folder",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="assets.AssetFolder",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="polymorphic_ctype",
            field=models.ForeignKey(
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="polymorphic_assets.asset_set+",
                to="contenttypes.ContentType",
            ),
        ),
        migrations.AddField(
            model_name="asset",
            name="tags",
            field=taggit_autosuggest.managers.TaggableManager(
                blank=True,
                help_text="Find tags by name or create new ones.",
                through="taggit.TaggedItem",
                to="taggit.Tag",
                verbose_name="Tags",
            ),
        ),
    ]
