# Generated by Django 1.10.5 on 2017-08-10 20:23


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0002_make_assetfolder_mptt"),
    ]

    operations = [
        migrations.AddField(
            model_name="asset",
            name="caption",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="asset",
            name="hide_caption",
            field=models.BooleanField(default=False),
        ),
    ]
