# Generated by Django 2.0.4 on 2018-04-03 23:37

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models

import ombucore.assets.validators


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0003_auto_20170810_2023"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asset",
            name="folder",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="The folder to put this asset into.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="folder",
                to="assets.AssetFolder",
                verbose_name="Asset Folder",
            ),
        ),
        migrations.AlterField(
            model_name="assetfolder",
            name="parent",
            field=mptt.fields.TreeForeignKey(
                blank=True,
                help_text="The parent folder to put this folder under.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="assets.AssetFolder",
                verbose_name="Parent Folder",
            ),
        ),
        migrations.AlterField(
            model_name="videoasset",
            name="transcript",
            field=models.FileField(
                blank=True,
                upload_to="",
                validators=[ombucore.assets.validators.FileExtensionValidator(("pdf",))],
                verbose_name="Transcript",
            ),
        ),
    ]
