# Generated by Django 2.0.2 on 2018-06-27 15:25

from django.db import migrations, models

import ombucore.assets.validators


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0004_auto_20180403_2337"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageasset",
            name="image",
            field=models.ImageField(
                height_field="height",
                help_text="Allowed image formats are PNG, JPG, GIF. Recommended minimum image size is 904px wide.",
                upload_to="img",
                validators=[
                    ombucore.assets.validators.FileExtensionValidator(whitelist=["PNG", "JPG", "JPEG", "GIF"])
                ],
                width_field="width",
            ),
        ),
    ]
