# Generated by Django 3.2.20 on 2023-08-30 21:06

from django.db import migrations, models

import ombucore.assets.validators


class Migration(migrations.Migration):
    dependencies = [
        ("assets", "0009_auto_20210922_1022"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageasset",
            name="image",
            field=models.ImageField(
                height_field="height",
                help_text=None,
                upload_to="img",
                validators=[
                    ombucore.assets.validators.FileExtensionValidator(
                        whitelist=[
                            "blp",
                            "bmp",
                            "dib",
                            "bufr",
                            "cur",
                            "pcx",
                            "dcx",
                            "dds",
                            "ps",
                            "eps",
                            "fit",
                            "fits",
                            "fli",
                            "flc",
                            "ftc",
                            "ftu",
                            "gbr",
                            "gif",
                            "grib",
                            "h5",
                            "hdf",
                            "png",
                            "apng",
                            "jp2",
                            "j2k",
                            "jpc",
                            "jpf",
                            "jpx",
                            "j2c",
                            "icns",
                            "ico",
                            "im",
                            "iim",
                            "jfif",
                            "jpe",
                            "jpg",
                            "jpeg",
                            "mpg",
                            "mpeg",
                            "tif",
                            "tiff",
                            "mpo",
                            "msp",
                            "palm",
                            "pcd",
                            "pdf",
                            "pxr",
                            "pbm",
                            "pgm",
                            "ppm",
                            "pnm",
                            "psd",
                            "qoi",
                            "bw",
                            "rgb",
                            "rgba",
                            "sgi",
                            "ras",
                            "tga",
                            "icb",
                            "vda",
                            "vst",
                            "webp",
                            "wmf",
                            "emf",
                            "xbm",
                            "xpm",
                        ]
                    )
                ],
                width_field="width",
            ),
        ),
    ]
