# Generated by Django 4.2.6 on 2025-07-16 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("assets", "0011_alter_asset_polymorphic_ctype"),
    ]

    operations = [
        migrations.DeleteModel(
            name="VideoAsset",
        ),
    ]
