from website.data_loading.transaction_templates import TransactionTemplate


class Template(TransactionTemplate):
    id = "accion_contra_el_hambre"
    label = "Accion Contra el Hambre"
    download_headers = [
        "contract",
        "period",
        "trans_date",
        "trans_no",
        "hash",
        "account",
        "cat2_change",
        "cat5_change",
        "cat5_lin_fin",
        "cat5_adjusted",
        "description_ii",
        "paid_by",
        "cat3",
        "cat4",
        "cat6",
        "cat7",
        "donor_acc",
        "donor_result",
        "text",
        "amount_eur",
        "curr",
        "tmp",
        "curr_amount",
        "donor_amount",
        "ex_r_1",
        "ex_r_2",
        "account_description",
        "external_dossier",
        "supplier_code",
        "supplier_name",
        "invoice_no",
        "updated_on",
        "order_id",
        "clean_report",
        "help5",
        "help6",
        "help7",
        "help8",
        "check_period",
        "client",
        "agrtid",
        "countif",
        "voucher_type",
        "voucher_no2",
        "account2",
        "dim_1",
        "contract3",
        "proyecto",
        "pay_date_voucher_no",
        "pay_method",
        "pay_date_voucher_no4",
        "pay_method5",
        "trans_date_2",
        "ext_inv_ref",
        "supplier",
        "supplier_name_2",
        "period6",
        "description",
        "currency2",
        "cur_amount",
        "amount",
        "_2",
        "_3",
        "hc",
        "alert",
    ]
    download_date_fields = (
        "trans_date",
        "updated_on",
        "pay_date_voucher_no",
        "pay_date_voucher_no4",
        "trans_date_2",
    )
    download_decimal_fields = (
        "amount_eur",
        "curr_amount",
        "donor_amount",
        "ex_r_1",
        "ex_r_2",
        "cur_amount",
        "amount",
    )
    source_date_formats = {
        "trans_date": ("%m/%d/%Y",),
    }
    canonical_field_sources = {
        "transaction_date": "trans_date",
        "country_code": "dim_1",
        "grant_code": "contract",
        "budget_line_code": "cat5_adjusted",
        "account_code": "account",
        "site_code": None,
        "sector_code": "cat6",
        "transaction_code": "trans_no",
        "transaction_description": "text",
        "currency_code": None,
        "budget_line_description": "description_ii",
        "amount": "amount_eur",
        "dummy_field_1": None,
        "dummy_field_2": None,
        "dummy_field_3": None,
        "dummy_field_4": None,
        "dummy_field_5": None,
    }

    required_source_fields = {
        "contract": "contract",
        "trans_date": "trans_date",
        "account": "account",
        "amount_eur": "amount_eur",
        "dim_1": "dim_1",
    }

    def normalize_rows(self, rows, analysis):
        return [
            {
                "transaction_date": row.get("trans_date", ""),
                "country_code": row.get("dim_1", ""),
                "grant_code": row.get("contract", ""),
                "budget_line_code": row.get("cat5_adjusted", ""),
                "account_code": row.get("account", ""),
                "site_code": "",
                "sector_code": row.get("cat6", ""),
                "transaction_code": row.get("trans_no", ""),
                "transaction_description": row.get("text", ""),
                "currency_code": "EUR",
                "budget_line_description": row.get("description_ii", ""),
                "amount": row.get("amount_eur", ""),
                "dummy_field_1": "",
                "dummy_field_2": "",
                "dummy_field_3": "",
                "dummy_field_4": "",
                "dummy_field_5": "",
            }
            for row in rows
        ]
