# Generated by Django 5.2.4 on 2025-07-25 05:21

import website.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
            CREATE COLLATION IF NOT EXISTS case_insensitive_email
              (provider = icu,
               locale = 'und-u-ks-level2',
               deterministic = false);
        """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="last login"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "email",
                    website.users.models.LowerEmailField(
                        db_collation="case_insensitive_email",
                        max_length=254,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="First and last name",
                        max_length=255,
                        verbose_name="Name",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("BASIC", "Basic User"), ("ADMIN", "Administrator")],
                        default="BASIC",
                        help_text="Designates whether the user can perform admin functionality within the app.  ",
                        max_length=255,
                        verbose_name="System Role",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "is_first_login",
                    models.BooleanField(
                        default=True,
                        help_text="Used internally.",
                        verbose_name="First Login Flag",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
            ],
            options={
                "verbose_name": "User",
                "verbose_name_plural": "Users",
                "ordering": ["name"],
            },
        ),
    ]
