# Generated by Django 5.2.4 on 2025-07-25 05:21

import django.db.models.deletion
import ombucore.admin.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0001_fresh_start"),
        ("website", "0001_fresh_start"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="primary_countries",
            field=ombucore.admin.fields.ManyToManyField(
                blank=True,
                help_text="User has write access to any analyses for these countries.",
                related_name="primary_countries_users",
                to="website.country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="primary_country",
            field=ombucore.admin.fields.ForeignKey(
                help_text="User has write access to any analyses for this country.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="primary_country_users",
                to="website.country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="secondary_countries",
            field=ombucore.admin.fields.ManyToManyField(
                blank=True,
                help_text="User has read access to any analyses in these countries.",
                related_name="secondary_countries_users",
                to="website.country",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
