# Generated by Django 5.2.4 on 2025-07-25 05:21

import any_urlfield.models.fields
import ckeditor.fields
import django.db.models.deletion
import ombucore.admin.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HelpItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("category", "Category"),
                            ("cost_type", "Cost Type"),
                            ("step", "Step"),
                            ("step_field", "Step Field"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("identifier", models.CharField(max_length=150)),
                (
                    "help_text",
                    ckeditor.fields.RichTextField(
                        blank=True,
                        help_text="If you leave this field blank, the contextual help item will not display in the application.",
                    ),
                ),
                (
                    "link",
                    any_urlfield.models.fields.AnyUrlField(
                        blank=True, max_length=300, null=True, verbose_name="More help"
                    ),
                ),
            ],
            options={
                "verbose_name": "Contextual Help",
                "verbose_name_plural": "Contextual Help",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="HelpTopic",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Help Topic",
                "verbose_name_plural": "Help Topics",
                "ordering": ("title",),
            },
        ),
        migrations.CreateModel(
            name="HelpPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("identifier", models.CharField(blank=True, max_length=150, null=True)),
                ("title", models.CharField(max_length=255)),
                ("body", ckeditor.fields.RichTextField(blank=True)),
                (
                    "path",
                    ombucore.admin.fields.UrlPathField(
                        blank=True,
                        help_text="This is the desired URL path for this page. If you leave this field blank, a path will be created for you by hyphenating your page title. If you choose to manually create a path, it may include letters, numbers, hyphens, and forward slashes (e.g., ‘help/define-step’).",
                        max_length=200,
                        verbose_name="Path",
                    ),
                ),
                (
                    "published",
                    models.BooleanField(
                        default=True,
                        help_text="When published, this page will appear in the help menu.",
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        help_text="This help page will appear alphabetically under this topic in the help menu when published.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="help.helptopic",
                        verbose_name="Section",
                    ),
                ),
            ],
            options={
                "verbose_name": "Help Page",
                "verbose_name_plural": "Help Pages",
                "ordering": ("title",),
            },
        ),
    ]
